INCDIR	=	../include
LIBS	=	petitdb
LIBDIR	= 	.

heapfile_test: 
	gcc -o heapfile_test -g -L$(LIBDIR) -l$(LIBS) -I$(INCDIR) heapfile_test.c
	
hashfile_test: 
	gcc -o hashfile_test -g -L$(LIBDIR) -l$(LIBS) -I$(INCDIR) hashfile_test.c

